### ISSUE TITLE
 Icon is missed: select_window_2

### ISSUE THREAD

**Issue by braindamagedman** [timmaffett/material_symbols_icons#21]

**Comment by timmaffett** [comment]
Hi @braindamagedman - there is a [bug currently](https://github.com/google/material-design-icons/issues/1706) in the official material symbols font repo that is preventing it from creating the fonts when a new icons are added.  This looks like it has been broken since February sometime.  Once the release pipeline for the material symbols repo is fixed then we will be able to release a new version of the material symbols icons package that contains all of the up to date icons.

**Comment by timmaffett** [comment]
@braindamagedman The official pipe line was finally fixed and I have published a new release that is up to date with all current icons in the official repo!
