### ISSUE TITLE
Absence of Material Symbol for 'pip' 

### ISSUE THREAD

**Issue by Peng-Qian** [timmaffett/material_symbols_icons#3]
Thanks for the awesome package, and it seems the pip symbol is missing there...

**Comment by timmaffett** [comment]
Thank you for reporting this!

I see that the `pip` icon is missing - 
https://fonts.google.com/icons?icon.style=Outlined&selected=Material+Symbols+Outlined:pip:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=pip

In investigating I have discovered that the `pip` code point ins missing from the code point files at https://github.com/google/material-design-icons/blob/master/variablefont/
as well as missing from the ttf fonts found there.   This is what the packages uses as the source of the icon fonts.  I have created a [PR #1517 at the material-design-icons github repo](https://github.com/google/material-design-icons/issues/1517)

As soon as the official fonts are updated with the missing icons I will release a package update!

**Comment by timmaffett** [comment]
It may help to go to the [Issue #1517](https://github.com/google/material-design-icons/issues/1517) and give it a thumbs up.

**Comment by timmaffett** [comment]
I have added code to the example app so that when it is running as a web app it places state references into the app url as query parameters so that a URL can be used to bring up the app in the state a user has left it.

Here is the URL to look at the [icons containing the string `pip`](https://timmaffett.github.io/material_symbols_icons/?query=pip&iconSize=48&fontType=outlined&fill=0&weight=400&grade=0&opticalSize=48)

**Comment by timmaffett** [comment]
@Peng-Qian  The https://github.com/google/material-design-icons repo was updated yesterday and the new fonts are now incorporated in the new 4.2659.0 version of the material_symbols_icons package.   

[show pip icon is now included](https://timmaffett.github.io/material_symbols_icons/?query=pip&iconSize=48&fontType=outlined&fill=0&weight=400&grade=0&opticalSize=48)

(The middle `2659` number now corresponds to the 2.659 version of the variable fonts being used).
