### ISSUE TITLE
'float_portrait' symbol doesn't show right

### ISSUE THREAD

**Issue by Mae623** [timmaffett/material_symbols_icons#33]
`  SwitchListTile(
              secondary:
                  Icon(SymbolsGet.get('float_portrait', SymbolStyle.outlined)),)`

<img width="26" alt="iShot_2024-09-02_17 27 06" src="https://github.com/user-attachments/assets/925dbb08-b3b9-4bde-9214-05682440436d">

Hi, the 'float_portrait' symbol doesn't show right. Hope to your answer. The best wish to you.

**Comment by timmaffett** [comment]
I think the correct name of the icon you are looking for is `float_portrait_2` 

If you go to this package's example:  https://timmaffett.github.io/material_symbols_icons/    and search for 'float' (or 'portrait') you will see the icon appear.  Clicking on an icon will place it's flutter code name on the clipboard: (in this case `Symbols.float_portrait_2` )
Using the SymbolsGet.get() api - which is really only included for icon lookup programs, the name will be 'float_portrait_2'.
(Your example you included would more simply be written as 
`SwitchListTile( secondary: Icon(Symbols.float_portrait_2),)`

Usually icons are just references with thru the Symbols class as things like `Symbols.float_portrait_2` or `Symbols.float_landscape_2`  (that is the companion icon for the portrait version)

Another caution about using the `SymbolsGet.get()` interface is that this will prevent Flutter from being able to do icon tree shaking and will force Flutter to included all varieties and versions of all icons in the Symbols package - around 20-30MB.

You want to use the Symbols.XXXXX  notation to reference icons because this will allow Flutter to ONLY INCLUDE the icons that you reference.  This is not possible if you are dynamically looking up icon references by string names using the `SymbolsGet.get()` api.

**Comment by Mae623** [comment]
> I think the correct name of the icon you are looking for is `float_portrait_2`
> 
> If you go to this package's example: https://timmaffett.github.io/material_symbols_icons/ and search for 'float' (or 'portrait') you will see the icon appear. Clicking on an icon will place it's flutter code name on the clipboard: (in this case `Symbols.float_portrait_2` ) Using the SymbolsGet.get() api - which is really only included for icon lookup programs, the name will be 'float_portrait_2'. (Your example you included would more simply be written as `SwitchListTile( secondary: Icon(Symbols.float_portrait_2),)`
> 
> Usually icons are just references with thru the Symbols class as things like `Symbols.float_portrait_2` or `Symbols.float_landscape_2` (that is the companion icon for the portrait version)
> 
> Another caution about using the `SymbolsGet.get()` interface is that this will prevent Flutter from being able to do icon tree shaking and will force Flutter to included all varieties and versions of all icons in the Symbols package - around 20-30MB.
> 
> You want to use the Symbols.XXXXX notation to reference icons because this will allow Flutter to ONLY INCLUDE the icons that you reference. This is not possible if you are dynamically looking up icon references by string names using the `SymbolsGet.get()` api.

Oh my God! 
Thank you very much. 
Sorry for my carelessness.
