### ISSUE TITLE
VSCode hover docs, further steps

### ISSUE THREAD

**Issue by devberkay** [timmaffett/material_symbols_icons#35]
What are further steps after downloading .ttf files locally to get hover docs :

> The dart docs and vscode hover docs now include icon preview (if you install [the three MaterialSymbols*.ttf fonts](https://github.com/google/material-design-icons/tree/master/variablefont) locally on your machine).

I've downloaded and then installed through fontbook but didn't work, further steps might be helping here

**Comment by timmaffett** [comment]
Thank you Berkay for raising this issue!
It turned out that I had been forgetting to use the `-s` flag to `update_package.dart` then I was generating the source files files.  (You can read about the process in `generator\README.md` if you are interested.)
The way I display the icons in the dart docs is by using inline SVG's that reference the corresponding font file and codepoint for each symbol.  This initially was experimental as I worked on a way to display the symbols, so I had it behind the `-s` flag.  At some point I started forgetting to include the `-s` when generating the source for each new font release.  I have updated `generator\README.md` so I will not be forgetting this in the future.

As you suggested I have also added some documentation to the package README.md to explain the easiest way to install the new fonts with each release.

You can upgrade to version 4.2800.2 ,  it now includes the correct dart doc comments to display the symbols.

Thanks again !

**Comment by timmaffett** [comment]
@devberkay Did you get it working ?

**Comment by devberkay** [comment]
Yes!! @timmaffett , the newest version (4.2800.2) fixed it,  thank you for quick response and update, amazing package and work.

**Comment by cedvdb** [comment]
Previews ain't displaying for me, will update here if I find the reason


<img width="1260" height="257" alt="Image" src="https://github.com/user-attachments/assets/64a65c82-4ae1-4310-8dbb-13efda5d9b3c" />

**Comment by timmaffett** [comment]
Hi @cedvdb   
   **I just reproduce the problem on a new mac book I have.   It appears that the problem is caused by the `install_material_symbols_icons_fonts` script no longer working on MacOSX - even though it appears to.
I ran the installer and checked my FontBook and I did not see the fonts installed.
I then manually install the fonts and then they do show up in FontBook and I see the icon previews working again.**

I will work to figure out why the font install script is no longer working and get the package updated.
In the mean time you can install the fonts manually from the package directory, they are in `/lib/fonts/` of the package.

-tim

(ORIGINAL reply I was typing out:) 
That is weird.  Basically how previews work is that there is a inline data url SVG file in the dart docs for each symbol.  This svg file references the corresponding font and the appropriate code point.  The SVG file should render correctly as long as the font is installed on the machine.   
   Originally I tried to reference the web font in the case it was not installed, but sandboxing of the svg file prevents any network connections from the svg file, so the font must be installed locally.
  You can directly see/edit the SVG file in the symbols.dart source code.

**Comment by timmaffett** [comment]
Added issue #43 for this new bug.

**Comment by timmaffett** [comment]
I am grateful for @cedvdb 's bug report in his comment because it allowed me to become aware that outside of my environment the MacOSX scripts were most likely failing because of lack of the executable flag.  New version chmod's +x on the scripts.

Version 4.2872.1 fixes the issue and 

```shell
dart pub global activate material_symbols_icons
install_material_symbols_icons_fonts
```

should now work properly
