### ISSUE TITLE
Absence of Material Symbol for 'Page Info'

### ISSUE THREAD

**Issue by nTerior** [timmaffett/material_symbols_icons#4]
Missing Material Symbol: `Page Info`
Code Point: `f614`

**Comment by timmaffett** [comment]
Thank you for reporting this!

I see that the `page_info` icon is missing - 
https://fonts.google.com/icons?icon.style=Outlined&selected=Material+Symbols+Outlined:pip:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=page+info

The page_info icon is missing from the codepoint and ttf fonts found on the [official google repo](https://github.com/google/material-design-icons/tree/master/variablefont) that the packages uses as the the source of the icon fonts.  I have created a [Issue #1517 at the material-design-icons github repo](https://github.com/google/material-design-icons/issues/1517)

As soon as the official fonts are updated with the missing icons I will release a package update!

**Comment by timmaffett** [comment]
It may help to go to the [Issue #1517](https://github.com/google/material-design-icons/issues/1517) and give it a thumbs up.

**Comment by timmaffett** [comment]
I have added code to the example app so that when it is running as a web app it places state references into the app url as query parameters so that a URL can be used to bring up the app in the state a user has left it.

Here is the URL to look at the [icons containing the string `page`](https://timmaffett.github.io/material_symbols_icons/?query=page&iconSize=48&fontType=outlined&fill=0&weight=400&grade=0&opticalSize=48)

**Comment by timmaffett** [comment]
@nTerior   The https://github.com/google/material-design-icons repo was updated yesterday and the new fonts are now incorporated in the new 4.2659.0 version of the material_symbols_icons package.   

[show page_info icon is now included](https://timmaffett.github.io/material_symbols_icons/?query=page_info&iconSize=48&fontType=outlined&fill=0&weight=400&grade=0&opticalSize=48)

(The middle `2659` number now corresponds to the 2.659 version of the variable fonts being used).
